version: '1.0'

networks:
  default:
    name: net-wallet

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api-user:
    container_name: api-user
    build: ./api-user
    restart: always
    ports:
      - 3003:3003
    env_file:
      - ./api-user/.env
    environment:
      - APISALDO=api-saldo

  api-saldo:
    container_name: api-saldo
    build: ./api-saldo
    restart: always
    ports:
      - 3001:3001
    env_file:
      - ./api-saldo/.env

  api-extrato:
    container_name: api-extrato
    build: ./api-extrato
    restart: always
    ports:
      - 3002:3002
    depends_on:
      - kafka
    environment:
      - ENVIRONMENT=docker
      - APILOCAL=localhost

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api-user
      - api-saldo
      - api-extrato
      - kafka
    environment:
      - ENVIRONMENT=docker
      - APILOCAL=localhost
      - APISALDO=api-saldo
      - APIEXTRATO=api-extrato
      - APIUSER=api-user

  client:
    container_name: client
    build: ./client
    depends_on:
      - api-user
      - api-saldo
      - api-extrato
      - api-gateway
    env_file:
      - ./client/.env
    volumes:
      - client-volume:/var/www/html

  nginx:
    container_name: nginx-wallet
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api-user
      - api-saldo
      - api-extrato
      - api-gateway
      - client

volumes:
  client-volume:
    name: client-volume
  kafka-volume:
    name: kafka-volume